@host=http://localhost:3000

// auth, users router
### 회원가입
POST {{host}}/api/users
Content-Type: application/json

{
  "email" : "test@example.com",
  "name" : "test",
  "password" : "1234",
  "confirmPassword" : "1234",
  "region": "독도"
}

### 로그인
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email" : "test@example.com",
  "password" : "1234"
}

### 로그아웃
POST {{host}}/api/auth/logout
Content-Type: application/json

### 내 정보 조회
get {{host}}/api/users
Content-Type: application/json 
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNzAyNTQyNjQ0LCJleHAiOjE3MDI1ODU4NDR9.-t6RtgFD-QsWc9WGwbz6YBRY3WFL5NutRn6oW5zKX7Y


### 내 정보 수정
PUT {{host}}/api/auth/mypage
Content-Type: application/json

{ 
  "name" : "test",
  "password" : "1234",
  "confirmPassword" : "1234",
  "region": "울릉도"
}

### 내 정보 삭제
DELETE {{host}}/api/users/mypage
Content-Type: application/json

{
  "email" : "test@example.com",
  "password" : "1234"
}

### 예약등록
POST {{host}}/api/reservation
Content-Type: application/json

{
  "petSitterId" : "1",
  "animal" : "dog",
  "company" : "test1",
  "date" : "2023-12-14T16:25:14.389Z",
  "intro" : "히히히"
}