@host=http://localhost:3000

// auth, users router
### 회원가입
POST {{host}}/api/users
Content-Type: application/json

{
  "email" : "visitor17564@kakao.com",
  "name" : "visitor",
  "email" : "test@example.com",
  "name" : "김장훈",
  "password" : "1234",
  "confirmPassword" : "1234",
  "region": "우리집"
}

### 로그인
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email" : "visitor17564@kakao.com",
  "password" : "1234"
}

### 로그아웃
POST {{host}}/api/auth/logout
Content-Type: application/json

### 내 정보 조회
get {{host}}/api/users/me
Content-Type: application/json 
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTcwMjYyNTU5NiwiZXhwIjoxNzAyNjY4Nzk2fQ.KKaLAD_lNoCc417taquuYJMY7OVl_kH8Bs8carfH4Ms


### 내 정보 수정
PUT {{host}}/api/users/me
Content-Type: application/json

{ 
  "name" : "숲튽훈",
  "password" : "1234",
  "confirmPassword" : "1234",
  "region": "울릉도"
}

### 내 정보 삭제
DELETE {{host}}/api/users/me
Content-Type: application/json

{
  "email" : "test@example.com",
  "password" : "1234"
}

### 예약등록
POST {{host}}/api/reservation
Content-Type: application/json

{
  "petSitterId" : "1",
  "animal" : "dog",
  "company" : "test1",
  "date" : "2023-12-14",
  "comment" : "히히히"
}

### 펫시터조회
get {{host}}/api/petSitter
Content-Type: application/json

### 펫시터조회 byId
get {{host}}/api/petSitter/id/1
Content-Type: application/json

### 펫시터검색
get {{host}}/api/petSitter/search?career=10&animal=dog
Content-Type: application/json

### 펫시터리뷰조회
get {{host}}/api/reviews/1
Content-Type: application/json

### 펫시터리뷰조회
get {{host}}/api/reservation/3
Content-Type: application/json

### 펫시터리뷰조회
get {{host}}/api/reservation/3
Content-Type: application/json